[package]
name = "scidub-cli"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
scidev = { path = "../scidev" }
scidev-book = { path = "../book" }
tokio = { version = "1.0", features = ["full"] }
clap = "4.5.32"
serde_json = "1.0.140"
itertools = "0.13"
walkdir = "2.5.0"
log = "0.4.27"
csv = "1.3.1"
serde_yml = "0.0.12"

[lints]
workspace = true
