[package]
name = "scidub-cli"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
async-net = "2.0.0"
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
scidev-resources = { path = "../resources" }
scidev-utils = { path = "../utils" }
scidev-common = { path = "../common" }
smol = "2.0.2"
clap = "4.5.32"
serde_json = "1.0.140"
itertools = "0.13"
walkdir = "2.5.0"
log = "0.4.27"

[lints]
workspace = true
