[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

# Disable some pedantic lints, at least for now
missing-errors-doc = "allow"
missing-panics-doc = "allow"
unused-async = "allow"
