[package]
name = "scidev-book"
version = "0.1.0"
edition = "2024"

[dependencies]
scidev = { path = "../scidev" }
serde = { version = "1.0.210", features = ["derive"] }
anyhow = "1.0.86"
itertools = "0.13.0"
thiserror = "1.0.63"
schemars = "1.0.4"
serde_json = "1.0.141"

[lints]
workspace = true
