[package]
name = "datalit-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
derive-syn-parse = "0.2.0"
proc-macro-crate = "3.3.0"
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = "2.0.106"

[lints]
