[package]
name = "scitool-cli"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sci-utils = { path = "../utils" }
sci-resources = { path = "../resources" }
scitool-script-loader = { path = "../script_loader" }
sci-header-gen = { path = "../header-gen" }
sci-common = { path = "../common" }
scitool-book = { path = "../book" }
anyhow = "1.0.86"
bitter = "0.7.0"
clap = { version = "4.5.16", features = ["derive"] }
itertools = "0.13.0"
maud = "0.26.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_yml = "0.0.12"
thiserror = "1.0.63"
schemars = { version = "0.8.22", features = ["derive_json_schema"] }

[lints]
workspace = true
