[package]
name = "scitool-cli"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scidev = { path = "../scidev" }
clap = { version = "4.5.16", features = ["derive"] }
anyhow = "1.0.86"
bitter = "0.7.0"
itertools = "0.13.0"
serde = { version = "1.0.210", features = ["derive"] }

[lints]
workspace = true
