include = [
  # If you want to have local, uncommitted configuration, put it in the
  # sibling `local.toml` file. It is .gitignored, and will be loaded
  # by default.
  { path = "local.toml", optional = true }
]

[alias]
# Add an alias for running the xtask binary
x = ["run", "-p", "xtask", "-q", "--"]