use std::{collections::BTreeMap, fmt::Display, path::PathBuf, str::FromStr, time::Duration};

use anyhow::Context;
use clap::{Parser, Subcommand};
use scidev::{ids::LineId, utils::serde::Sha256Hash};
use sciproj::{
    book::{RoleId, file_format},
    build::audio::compile_audio_base,
    path::relpath::{RelPath, RelPathBuf, Segment},
    resources::AudioClip,
};
use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Error};

use crate::{
    data::{DataFormat, load_data, store_data},
    project::{Manifest, Project},
};

/// A utility for managing and building an SCI fan-dub project.
#[derive(Debug, Parser)]
#[clap(version, about)]
pub(crate) struct Cli {
    #[command(subcommand)]
    command: Command,
}

impl Cli {
    pub(crate) fn run(self) -> anyhow::Result<()> {
        self.command.run()
    }
}

#[derive(Debug, Subcommand)]
enum Command {
    Init(Init),
    Script(ScriptSubCommand),
    Build(Build),
    GameData(GameData),
}

impl Command {
    fn run(self) -> anyhow::Result<()> {
        match self {
            Self::Init(init) => init.run(),
            Self::Script(s) => s.run(),
            Self::Build(build) => build.run(),
            Self::GameData(game_data) => game_data.run(),
        }
    }
}

const INIT_GIT_IGNORE: &str = "\
# Generated by `scidub init`
/build/
/game_files/
!/game_files/.gitkeep
";

const INIT_SCIDUB_TOML: &str = "
# Generated by `scidub init`
game_data = \"game_data\"
";

/// Creates a new project root in the specified directory.
///
/// By default, the project root is created in the current directory.
#[derive(Debug, Parser)]
struct Init {
    #[clap(index = 1)]
    root: Option<PathBuf>,

    #[clap(long)]
    game_data: Option<PathBuf>,
}

impl Init {
    fn run(self) -> anyhow::Result<()> {
        let root = self.root.map_or_else(std::env::current_dir, Ok)?;

        anyhow::ensure!(root.exists(), "Project directory does not exist.");
        anyhow::ensure!(
            std::fs::read_dir(&root)?.next().is_none(),
            "Project directory is not empty."
        );

        eprintln!("Creating project under {}", root.display());
        let git_ignore_path = root.join(".gitignore");
        let project_config_path = root.join("scidub.toml");
        if !git_ignore_path.exists() {
            std::fs::write(&git_ignore_path, INIT_GIT_IGNORE)?;
        }

        if !project_config_path.exists() {
            std::fs::write(&git_ignore_path, INIT_SCIDUB_TOML)?;
        }

        let game_data_path = root.join("game_data");
        std::fs::create_dir_all(&game_data_path)?;
        std::fs::write(game_data_path.join(".gitkeep"), "")?;

        // if !root.join(".git") {}

        Ok(())
    }
}

/// Work with game voice scripts.
#[derive(Debug, Parser)]
struct ScriptSubCommand {
    #[command(subcommand)]
    sub_command: ScriptCommand,
}

impl ScriptSubCommand {
    fn run(self) -> anyhow::Result<()> {
        self.sub_command.run()
    }
}

#[derive(Debug, Subcommand)]
enum ScriptCommand {
    Export(ExportScript),
}

impl ScriptCommand {
    fn run(self) -> anyhow::Result<()> {
        match self {
            Self::Export(export) => export.run(),
        }
    }
}

#[derive(Debug, clap::Args)]
struct GlobalConfigArgs {
    /// Provides an explicit root for the project.
    #[arg(long)]
    project_root: Option<PathBuf>,
}

impl GlobalConfigArgs {
    fn load_env(self) -> anyhow::Result<Project> {
        let project = if let Some(project_root) = self.project_root {
            Project::new(project_root)
        } else {
            Project::new_from_path(&std::env::current_dir()?)?
        };

        Ok(project)
    }
}

struct ToFromStringSerde;

impl ToFromStringSerde {
    pub(crate) fn serialize<T, S>(value: &T, serializer: S) -> Result<S::Ok, S::Error>
    where
        T: ToString,
        S: Serializer,
    {
        value.to_string().serialize(serializer)
    }

    pub(crate) fn deserialize<'de, T, D>(deserializer: D) -> Result<T, D::Error>
    where
        T: FromStr,
        T::Err: Display,
        D: Deserializer<'de>,
    {
        let s: &str = Deserialize::deserialize(deserializer)?;
        T::from_str(s).map_err(D::Error::custom)
    }
}

#[derive(Debug, Deserialize)]
struct LineMapping {
    #[serde(with = "ToFromStringSerde")]
    line_id: LineId,
    clip_path: RelPathBuf,
    clip_start_ns: Option<u64>,
    clip_end_ns: Option<u64>,
}

/// Builds a resource patch from a target.
#[derive(Debug, Parser)]
pub(crate) struct Build {
    #[command(flatten)]
    env: GlobalConfigArgs,
    /// The name of the game target to export.
    #[arg(index = 1, conflicts_with = "line_mapping", required = true)]
    target: Option<String>,

    #[arg(short = 'm', long, required = true)]
    line_mapping: Option<PathBuf>,

    #[arg(long)]
    audio_files: Option<PathBuf>,

    #[arg(short, long)]
    output: Option<PathBuf>,

    #[arg(short = 'n', long)]
    dry_run: bool,
}

impl Build {
    pub(crate) fn run(self) -> anyhow::Result<()> {
        let project = self.env.load_env()?;

        let config = project.config()?;
        let book = project.book()?;

        let (line_mapping_path, target_name) = if let Some(target) = &self.target {
            let Some(target_config) = config.targets().get(target) else {
                anyhow::bail!("Target {target} not found")
            };
            (
                target_config.line_mapping().to_std_path(project.root()),
                target.as_str(),
            )
        } else {
            let Some(line_mapping) = &self.line_mapping else {
                unreachable!("ensured by clap");
            };
            (line_mapping.clone(), "default")
        };

        let line_mappings: Vec<LineMapping> =
            load_data(&line_mapping_path, &crate::data::DataFormat::Csv)?;

        let audio_files_root = self.audio_files.unwrap_or_else(|| {
            config
                .audio_files_root()
                .unwrap_or(RelPath::new(""))
                .to_std_path(project.root())
        });

        let mut line_map = BTreeMap::new();
        for line_mapping in line_mappings {
            let clip = AudioClip {
                start_us: line_mapping.clip_start_ns,
                end_us: line_mapping.clip_end_ns,
                path: line_mapping.clip_path.to_std_path(&audio_files_root),
            };

            line_map
                .insert(line_mapping.line_id, clip)
                .ok_or_else(|| anyhow::anyhow!("Duplicate line from project."))?;
        }

        // Check that every line in the book is present in the line map.
        let mut non_present_clips = Vec::new();

        for line in book.lines() {
            let id = line.id();
            if !line_map.contains_key(&id) {
                non_present_clips.push(id);
            }
        }

        let mut unused_clips = Vec::new();
        for id in line_map.keys() {
            if book.get_line(*id).is_none() {
                unused_clips.push(*id);
            }
        }

        // TODO: Have an option to generate a placeholder
        if !non_present_clips.is_empty() {
            anyhow::bail!(
                "The following {} lines are not present in the line map: {}",
                non_present_clips.len(),
                non_present_clips
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<String>>()
                    .join(", ")
            );
        }

        if !unused_clips.is_empty() {
            anyhow::bail!(
                "The following {} clips are not used in the book: {}",
                unused_clips.len(),
                unused_clips
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<String>>()
                    .join(", ")
            );
        }

        let target_relpath = Segment::try_new(target_name)
            .ok_or_else(|| anyhow::anyhow!("Target name must be a valid relative path segment"))?;

        let base_output_dir = self.output.unwrap_or_else(|| {
            config
                .build_dir()
                .unwrap_or(RelPath::new("build"))
                .join(target_relpath)
                .to_std_path(project.root())
        });

        if self.dry_run {
            return Ok(());
        }

        let rt = tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()?;
        rt.block_on(compile_audio_base(&line_map, &base_output_dir))?;

        rt.shutdown_timeout(Duration::from_secs(1));

        Ok(())
    }
}

#[derive(Debug, Parser)]
struct ExportScript {
    #[clap(subcommand)]
    command: ExportScriptSubcommand,
}

impl ExportScript {
    fn run(self) -> anyhow::Result<()> {
        match self.command {
            ExportScriptSubcommand::Lines(export_lines) => export_lines.run(),
            ExportScriptSubcommand::Book(export_book) => export_book.run(),
        }
    }
}

#[derive(Debug, Subcommand)]
enum ExportScriptSubcommand {
    Lines(ExportLines),
    Book(ExportBook),
}

#[derive(Debug, Serialize, Deserialize)]
struct ScriptLineRecord {
    #[serde(with = "ToFromStringSerde")]
    id: LineId,
    line_text: String,
    #[serde(with = "ToFromStringSerde")]
    role_id: RoleId,
}

/// Exports all spoken lines in a tabular format.
///
/// Includes a unique ID for each line, the role ID for the line, and the
/// text of the line.
///
/// The default format is CSV, which includes a header row. Field names are
/// `id`, `role_id`, and `line_text`
#[derive(Debug, Parser)]
struct ExportLines {
    #[command(flatten)]
    env: GlobalConfigArgs,

    #[clap(short = 'o', long, required = true)]
    output: PathBuf,
}

impl ExportLines {
    fn run(self) -> anyhow::Result<()> {
        let project = self.env.load_env()?;

        let book = project
            .book_opt()?
            .ok_or_else(|| anyhow::anyhow!("No book is configured for the project."))?;

        let mut script_lines = Vec::new();
        for line in book.lines() {
            script_lines.push(ScriptLineRecord {
                id: line.id(),
                line_text: line.text().to_plain_text(),
                role_id: line.role().id(),
            });
        }

        store_data(&self.output, &script_lines[..], &DataFormat::Csv)?;
        Ok(())
    }
}

/// Exports a Book file in JSON format.
///
/// This generates a representation of the entire voice script that can be
/// used in the VO Script web app. Lines are extracted from the game data.
#[derive(Debug, Parser)]
struct ExportBook {
    #[command(flatten)]
    env: GlobalConfigArgs,

    #[clap(short = 'o', long, required = true)]
    output: PathBuf,
}

impl ExportBook {
    fn run(self) -> anyhow::Result<()> {
        let project = self.env.load_env()?;
        let book = project.book()?;

        let output = std::fs::File::create(&self.output)?;

        file_format::serialize_book(book, &mut serde_json::Serializer::new(output))?;
        Ok(())
    }
}

/// Manage game resource data.
#[derive(Debug, Parser)]
struct GameData {
    #[clap(subcommand)]
    command: GameDataSubcommand,
}

impl GameData {
    fn run(self) -> anyhow::Result<()> {
        match self.command {
            GameDataSubcommand::CreateManifest(c) => c.run(),
            GameDataSubcommand::Validate(v) => v.run(),
        }
    }
}

#[derive(Debug, Subcommand)]
enum GameDataSubcommand {
    CreateManifest(CreateManifest),
    Validate(ValidateManifest),
}

/// Create a manifest for the current game data.
///
/// To ensure that any resources are being taken from the same source,
/// without checking in any resources, the project can track a
/// manifest file, which records the set of files in the game data, as well
/// as its hash.
#[derive(Debug, Parser)]
struct CreateManifest {
    #[command(flatten)]
    env: GlobalConfigArgs,
}

impl CreateManifest {
    fn run(self) -> anyhow::Result<()> {
        let project = self.env.load_env()?;
        let game_path = project.game_path()?;

        let walker = walkdir::WalkDir::new(game_path)
            .follow_links(false)
            .follow_root_links(false);

        let mut manifest = Manifest::new();
        for entry in walker {
            let entry = entry?;
            if !entry.file_type().is_file() {
                continue;
            }
            let file = std::fs::File::open(entry.path())?;
            let relative_path = entry.path().strip_prefix(game_path)?;
            manifest.add_from_reader(RelPath::from_std_path(&relative_path), file)?;
        }

        let manifest_path = project.manifest_path()?;

        let mut output = std::fs::File::create(manifest_path)?;
        serde_json::to_writer_pretty(&mut output, &manifest)?;
        Ok(())
    }
}

/// Validate that the current game data matches the manifest.
///
/// This command can be used to detect if the game data has changed since
/// the last time the manifest was created.
#[derive(Debug, Parser)]
struct ValidateManifest {
    #[command(flatten)]
    env: GlobalConfigArgs,
}

impl ValidateManifest {
    fn run(self) -> anyhow::Result<()> {
        let project = self
            .env
            .load_env()
            .context("while loading project".to_string())?;
        let manifest = project.manifest()?;
        let game_path = project.game_path()?;

        let mut entries = manifest.entries().clone();

        let walker = walkdir::WalkDir::new(game_path)
            .follow_links(false)
            .follow_root_links(false);

        for entry in walker {
            let entry = entry?;
            if !entry.file_type().is_file() {
                continue;
            }
            let file = std::fs::File::open(entry.path())
                .context(format!("Could not open file {}", entry.path().display()))?;
            let (file_hash, _) = Sha256Hash::from_stream_hash(file)?;
            let relative_path: &RelPath = entry.path().strip_prefix(game_path)?.try_into()?;
            let Some(manifest_hash) = entries.remove(relative_path) else {
                anyhow::bail!("Found game file not in manifest: {relative_path}");
            };

            if manifest_hash != file_hash {
                anyhow::bail!("Game file {relative_path} is different from version in manifest.");
            }
        }

        if !entries.is_empty() {
            anyhow::bail!(
                "The following files are present in the manifest but not found in the game directory: {}",
                entries
                    .keys()
                    .map(ToString::to_string)
                    .collect::<Vec<String>>()
                    .join(", ")
            );
        }

        eprintln!("Files at {} match the manifest.", game_path.display());
        Ok(())
    }
}
