[package]
name = "scidev-script-loader"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
bytes = "1.10.1"
scidev-resources = { path = "../resources" }
scidev-utils = { path = "../utils" }

[lints]
workspace = true
