on: workflow_dispatch
permissions:
  contents: read
jobs:
  # This may be insane, but I found it a lot easier to cross-compile
  # ffmpeg for Windows than to use a Windows VM or Visual Studio.
  build_ffmpeg:
    strategy:
      matrix:
        platform: [windows, linux, macos]
        include:
          - platform: windows
            host_os: ubuntu
            target_os: win64
            target_bin: ffmpeg.exe
          - platform: linux
            host_os: ubuntu
            target_os: linux
            target_bin: ffmpeg
          - platform: macos
            host_os: macos
            target_os: darwin
            target_bin: ffmpeg
    runs-on: ${{ matrix.host_os }}-latest
    env:
      REPO_ROOT: "${{ github.workspace }}/src/scidub"
    steps:
      - uses: actions/checkout@v6
        with:
          path: ${{ env.REPO_ROOT }}
      - name: Setup envvars
        run: |
          export DIST_ROOT="$REPO_ROOT/dist"
          export PLAT_ROOT="$DIST_ROOT/plat/${{ matrix.platform }}"
          export INSTALL_PREFIX="${{ github.workspace }}/install"
          export TARGET_OS=${{ matrix.target_os }}
          echo "DIST_ROOT=$DIST_ROOT" >> $GITHUB_ENV
          echo "PLAT_ROOT=$PLAT_ROOT" >> $GITHUB_ENV
          echo "INSTALL_PREFIX=$INSTALL_PREFIX" >> $GITHUB_ENV
          echo "TARGET_OS=$TARGET_OS" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          if [[ -f "$PLAT_ROOT/install-deps.sh" ]]; then
            echo "Installing platform deps"
            . "$PLAT_ROOT/install-deps.sh"
          else
            echo "No platform deps found at $PLAT_ROOT/install-deps.sh"
          fi
      - uses: actions/checkout@v6
        with:
          repository: "xiph/ogg"
          path: "src/libogg"
      - uses: actions/checkout@v6
        with:
          repository: "xiph/vorbis"
          path: "src/libvorbis"
      - uses: actions/checkout@v6
        with:
          repository: "FFmpeg/FFmpeg"
          path: "src/ffmpeg"
      - name: Build and install ogg
        working-directory: src/libogg
        run: |
          declare -a CMAKE_ARGS
          . "$DIST_ROOT/cmake-cfg.sh"
          if [[ -f "$PLAT_ROOT/cmake-cfg.sh" ]]; then
            . "$PLAT_ROOT/cmake-cfg.sh"
          fi
          cmake -Bbuild "${CMAKE_ARGS[@]}"
          cmake --build build --config Release
          cmake --install build --config Release
      - name: Build and install vorbis
        working-directory: src/libvorbis
        run: |
          declare -a CMAKE_ARGS
          . "$DIST_ROOT/cmake-cfg.sh"
          if [[ -f "$PLAT_ROOT/cmake-cfg.sh" ]]; then
            . "$PLAT_ROOT/cmake-cfg.sh"
          fi
          cmake -Bbuild "${CMAKE_ARGS[@]}"
          cmake --build build --config Release
          cmake --install build --config Release
      - name: Build and install ffmpeg
        working-directory: src/ffmpeg
        run: |
          export PKG_CONFIG_PATH="$INSTALL_PREFIX/lib/pkgconfig"
          declare -a FFMPEG_CONF_ARGS
          . "$DIST_ROOT/ffmpeg-cfg.sh"
          if [[ -f "$PLAT_ROOT/ffmpeg-cfg.sh" ]]; then
            . "$PLAT_ROOT/ffmpeg-cfg.sh"
          fi
          ./configure "${FFMPEG_CONF_ARGS[@]}"
          make -j8
      - name: Upload ffmpeg bin
        uses: pyTooling/upload-artifact@v1.10.0
        with:
          working-directory: src/ffmpeg
          investigate: true
          name: ffmpeg-bin-${{ matrix.platform }}
          path: ${{ matrix.target_bin }}

  build_espeak:
    strategy:
      matrix:
        platform: [windows, linux, macos]
        include:
          - platform: windows
            os: windows
            espeak_base: espeak-ng/build/src/Release
            espeak_bin: espeak-ng.exe
            shell: C:\msys64\usr\bin\bash.exe {0}
          - platform: linux
            os: ubuntu
            espeak_base: espeak-ng/build/src
            espeak_bin: espeak-ng
            shell: bash
          - platform: macos
            os: macos
            espeak_base: espeak-ng/build/src
            espeak_bin: espeak-ng
            shell: bash
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "espeak-ng/espeak-ng"
          ref: "fbe4b3764285c35b1f035cb8d09ad9fc19f71c30"
          path: "espeak-ng"
      - working-directory: espeak-ng
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DUSE_LIBPCAUDIO=OFF -DBUILD_SHARED_LIBS=OFF
          cmake --build build --config Release
      - uses: pyTooling/upload-artifact@v1.10.0
        with:
          working-directory: ${{ matrix.espeak_base }}
          investigate: true
          name: espeak-bin-${{ matrix.platform }}
          path: ${{ matrix.espeak_bin }}
      - uses: pyTooling/upload-artifact@v1.10.0
        with:
          working-directory: espeak-ng/build
          investigate: true
          name: espeak-data-${{ matrix.platform }}
          path: espeak-ng-data/**

  build_scidub:
    strategy:
      matrix:
          platform: [windows, linux, macos]
          include:
            - platform: windows
              os: windows
              exe_suffix: .exe
            - platform: linux
              os: ubuntu
              exe_suffix: 
            - platform: macos
              os: macos
              exe_suffix: 
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: scidev
      - uses: actions-rust-lang/setup-rust-toolchain@v1.16.1
        with:
          toolchain: 1.96.0
      - working-directory: scidev
        run: cargo build --bin scidub --release --no-default-features
      - uses: pyTooling/upload-artifact@v1.10.0
        with:
          working-directory: scidev/target/release
          investigate: true
          name: scidub-bin-${{ matrix.platform }}
          path: scidub${{ matrix.exe_suffix }}

  build_scinc:
    strategy:
      matrix:
          platform: [windows, linux, macos]
          include:
            - platform: windows
              os: windows
              exe_suffix: .exe
            - platform: linux
              os: ubuntu
              exe_suffix: 
            - platform: macos
              os: macos
              exe_suffix: 
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: naerbnic/sci-compiler
          path: src/scinc
      - name: Run Build
        working-directory: src/scinc
        run: |
          bazel build -c opt //packaging:scinc_tgz
      - uses: actions/upload-artifact@v7
        with:
          archive: false
          name: scinc-tgz-${{ matrix.platform }}
          path: src/scinc/bazel-bin/packaging/scinc.tgz
      - name: Repackage
        shell: bash
        run: |
          mkdir -p output
          cd output
          tar xzf ../src/scinc/bazel-bin/packaging/scinc.tgz
          # This is supposed to be a tool, so we move the binaries to libexec,
          # and move the include directory under a package-specific share directory.
          mv bin libexec
          if [[ ! -z "${{ matrix.exe_suffix }}" ]]; then
            mv libexec/scinc libexec/scinc${{ matrix.exe_suffix }}
          fi
          mkdir -p share/scinc
          mv include share/scinc
          ls -lR .
      - uses: pyTooling/upload-artifact@v1.10.0
        with:
          working-directory: output
          investigate: true
          name: scinc-${{ matrix.platform }}
          path: "**"
  
  build_dist:
    needs: [build_ffmpeg, build_espeak, build_scidub, build_scinc]
    strategy:
      fail-fast: false
      matrix:
        platform: [windows, linux, macos]
        include:
          - platform: windows
            os: windows
            exe_suffix: .exe
          - platform: linux
            os: ubuntu
          - platform: macos
            os: macos
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: pyTooling/download-artifact@v1.9.0
        with:
          name: scidub-bin-${{ matrix.platform }}
          path: root/bin
      - uses: pyTooling/download-artifact@v1.9.0
        with:
          name: ffmpeg-bin-${{ matrix.platform }}
          path: root/libexec
      - uses: pyTooling/download-artifact@v1.9.0
        with:
          name: espeak-bin-${{ matrix.platform }}
          path: root/libexec
      - uses: pyTooling/download-artifact@v1.9.0
        with:
          name: espeak-data-${{ matrix.platform }}
          path: root/share/espeak-ng
      - uses: pyTooling/download-artifact@v1.9.0
        with:
          name: scinc-${{ matrix.platform }}
          path: root
      - uses: pyTooling/upload-artifact@v1.10.0
        with:
          working-directory: root
          investigate: true
          name: scidub-dist-${{ matrix.platform }}
          path: "**"
  test_dist:
    needs:
      - build_dist
    strategy:
      fail-fast: false
      matrix:
        platform: [windows, linux, macos]
        include:
          - platform: windows
            os: windows
            exe_suffix: .exe
          - platform: linux
            os: ubuntu
          - platform: macos
            os: macos
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: pyTooling/download-artifact@v1.9.0
        with:
          name: scidub-dist-${{ matrix.platform }}
          path: root
      - name: Test Distribution
        run: |
          echo "Smoke test: Running the tool directly"
          root/bin/scidub${{ matrix.exe_suffix }} --version
          echo "Running the check-distribution command"
          root/bin/scidub${{ matrix.exe_suffix }} check-distribution \
            --required-tools ffmpeg,espeak,scinc 

  create_dist:
    needs:
      - test_dist
    strategy:
      fail-fast: false
      matrix:
        platform: [windows, linux, macos]
        include:
          - platform: windows
            os: windows
            archive_ext: zip
            exe_suffix: .exe
            tar_bin: /c/Windows/System32/tar.exe
          - platform: linux
            os: ubuntu
            archive_ext: tar.xz
            tar_bin: tar
          - platform: macos
            os: macos
            archive_ext: tar.xz
            tar_bin: gtar
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    env:
      RELEASE_FILE_NAME: scidub-release-${{ matrix.platform }}.${{ matrix.archive_ext }}
    steps:
      - uses: pyTooling/download-artifact@v1.9.0
        with:
          name: scidub-dist-${{ matrix.platform }}
          path: root
      - name: Create Release Archive
        run: |
          ${{ matrix.tar_bin }} -C root -a -cf "$GITHUB_WORKSPACE/$RELEASE_FILE_NAME" .
      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ env.RELEASE_FILE_NAME }}
          
          
        
      

      

